### PR TITLE
Adding new bio file for egsilber

### LINKED ISSUE #23: Add Bio for egsilber
Name: Ed
* Bullet 1
* Bullet 2
@githubteacher

### PR DESCRIPTION
**Pull request by egsilber**
This pull request fixes/resolves #23 
- [x] task1
- [ ] task 2

### CODE REVIEW

**Comment by egsilber** [comment]
Take a look at my pull request? @rhug

**Comment by egsilber** [comment]
Take a look at my pull request? @nameche

**Comment by egsilber** [comment]
Fixed formatting, added favorite food and origin @nameche @rhug

**Comment by nameche** [comment]
Excellent! Thanks @egsilber

**Pull request merged**
